name: Unit tests

on:
  push:
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.0.0'
        id: go

      - name: Go mod verify
        run: go mod verify

      - name: Run unit tests
        run:
          make test
